deployment:
  tasks:
    - echo "🔁 Starting deployment..."

    - export NODE_ENV=production

    - echo "📦 Installing backend dependencies..."
    - cd backend
    - npm install

    - echo "🚀 Restarting backend app with PM2..."
    - pm2 restart server.js --name "backend-app" || pm2 start server.js --name "backend-app"

    - echo "🧱 Building frontend..."
    - cd ../frontend
    - npm install
    - npm run build

    - echo "🧹 Cleaning old frontend files..."
    - rm -rf ../public_html/*

    - echo "📤 Deploying frontend to public_html..."
    - cp -r build/* ../public_html/

    - echo "✅ Deployment finished!"
