deployment:
  tasks:
    - echo "🔁 Starting deployment..."

    # Set production environment
    - export NODE_ENV=production

    # Backend setup
    - echo "📦 Installing backend dependencies..."
    - cd backend
    - npm install

    # Restart backend using PM2
    - echo "🚀 Restarting backend app with PM2..."
    - pm2 restart server.js --name "backend-app" || pm2 start server.js --name "backend-app"

    # Frontend setup
    - echo "🧱 Building frontend..."
    - cd ../frontend
    - npm install
    - npm run build

    # Clean old frontend build from public_html
    - echo "🧹 Cleaning old frontend files..."
    - rm -rf ../public_html/*

    # Copy new build to public_html
    - echo "📤 Deploying frontend to public_html..."
    - cp -r build/* ../public_html/

    - echo "✅ Deployment finished!"
