name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{node238.r-usdatacenter.register.lk}}
        username: ${{oakroots}}
        key: ${{-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA0O+QNyEht6MA33Y9uHaXS7onsnLEKbjMb5bXBciFJcb5UW8lToUh
xe7Xku1kjs6EzlndLjaBv/reZmH5pimjGWhhrIltTuVoymVb/kOU5jp7oIjDOBbuFyh196
LfKxQJ45UzwnZUMnclqsG5CLIyjDi/F6y/7702s8DQkRXGo2ITTskXcN+86+d7XfypJ2cd
SEpJeVROsU64ydsq0lfwIb6Q+mRkEbzwVguK2t0UKk6B4lmx2DFtp3M/WbYy4w6H/2YyRC
e69HGMWtFqFT76LSHpFNmQAmMSWghT/TtqZBcjvb//oXq0iJgp6FQytqnGY+qz57rET3uK
OrpCEAafCcaA1jcTNwYu0Gx3k41o5vTFluqGH2Nh52+etlqAGS5p85D1XwSnYSyXmhN+lX
87wndL/xSToCeaNtT6KEeSCKA8cOd8cZNQxhbL2P1s+VWJ+2r+Ox7etDtYIe+6V6oGsydx
qESbbvcdbv/lqKgT3OfpXqHjFPTIaW5OB4H3Ya28XirUO8AxjdAe81FGrOoUh5ylPMM3mB
JsllPyGf4YtVfv7d4YM7x/wZSaQpRhkBlTYiA/O7M4zkgt1GXxvVNQTh63bUXUPxdcIC8X
Z9kcKpfjL2fmNWtH0TYJDAK4ZR3YpxpsfC+1u06KsPPn3q567rSZh9q8TqwunxgFDVYR+w
UAAAdYEQP1/hED9f4AAAAHc3NoLXJzYQAAAgEA0O+QNyEht6MA33Y9uHaXS7onsnLEKbjM
b5bXBciFJcb5UW8lToUhxe7Xku1kjs6EzlndLjaBv/reZmH5pimjGWhhrIltTuVoymVb/k
OU5jp7oIjDOBbuFyh196LfKxQJ45UzwnZUMnclqsG5CLIyjDi/F6y/7702s8DQkRXGo2IT
TskXcN+86+d7XfypJ2cdSEpJeVROsU64ydsq0lfwIb6Q+mRkEbzwVguK2t0UKk6B4lmx2D
Ftp3M/WbYy4w6H/2YyRCe69HGMWtFqFT76LSHpFNmQAmMSWghT/TtqZBcjvb//oXq0iJgp
6FQytqnGY+qz57rET3uKOrpCEAafCcaA1jcTNwYu0Gx3k41o5vTFluqGH2Nh52+etlqAGS
5p85D1XwSnYSyXmhN+lX87wndL/xSToCeaNtT6KEeSCKA8cOd8cZNQxhbL2P1s+VWJ+2r+
Ox7etDtYIe+6V6oGsydxqESbbvcdbv/lqKgT3OfpXqHjFPTIaW5OB4H3Ya28XirUO8Axjd
Ae81FGrOoUh5ylPMM3mBJsllPyGf4YtVfv7d4YM7x/wZSaQpRhkBlTYiA/O7M4zkgt1GXx
vVNQTh63bUXUPxdcIC8XZ9kcKpfjL2fmNWtH0TYJDAK4ZR3YpxpsfC+1u06KsPPn3q567r
SZh9q8TqwunxgFDVYR+wUAAAADAQABAAACABCVtj1iCw1KykLICH3a0AdUp1pcuMx/sklN
+xMm8nFoD29S4sO5AVAhtYlLVcGY4WWIhZbpqw1O/8C3GJGDhEJRN6ZHTF7IYAk82CYL6E
cJhQ8I/By42T0LsFLat1tHM8JrHAOHerHSJQfJE9koXVHQc/667uC8BMUU/O6fVg1Zt3hN
XGfQeBcZC1ZlEWpNdD9s7NMi3ueSfPbs8kO7HkEXduZL+hOHC2QmdhG0cyl+jNnSTocqOU
Q4UOLb+cMYlVwFGTVcGqoqVJP67oWcN6XwfKdz3ktfi4aLsFsNZdRnGnuxQLyT2GkapwJI
TgmThWogqGzbCu0s5xvioA7UmmK6qqaMZs3OlIcmLHdhoT4s1IwOQhNVh2UQcAAqocAC5V
AkcRY/zEAdhftIYnvl8cppqesmXP+jRgpogtcIU9ywWloefjfcymAkL3KSkPBOB1QA3mzW
8XBAsA8vb2l5om+CCNupO5Cb/fLP5VkE5Vs6+La5mSSyFHuMLOaqcWWie0YhlrUQR58OEv
DtCSJLJdaWt8BPhWYF4jCvb/iVra+JdX6xcBV/TkrsSHYfWnTBc7fiF2YpCwn49ru0rif3
PMUaP92XzdMcu/qgKTAFXJSHI3a0i44fYuKzWZ+EpftAs/tHVYwBJ6ZF1QseqInaWtRpEr
4AMwsSsqNnXgGfP0xrAAABAQDDLT/a0/7OHcLMQhR/o9RikBWrI/2shPfO51ov0i3BYFzZ
M3pHwUQT916JbV61BRnl5gVfhW7xknkgVQuK0soLqPM6hyh/tJW8iyTX9XTbaj7wrsSKep
NzZuFIz/rUhsbNIMaRUTlEhsBykPHOieJ0sDdaKZFfmJgkzCxeXPj0FGBPrm8MqE0BAmJ3
J+lL7FnBI63B8vYjAv4jbxc9DF1+OuPd9svEHWHX2IvuAliGF52semvMM1nV8g8wVVDzsM
PyVeZSUY+6kH7frZJRAfL1V/pZslUAZys9lcMitc/++utBH2Cqvc/at2JWJWG+JqHlPs8g
ihcHz+m9tUl6DObvAAABAQDy0VB5Mu+DqYEPJqG3B6d7fAqs7ktQbFx8ZRQa2EBxyA9Na1
U9lmaY5TogoD/6foHrfkzbf31g1hM3yR61o/7PVHo9rcC7rRzI8cUt7ig1A4ffUenMuuK3
LONHc1NSQTW2K9qp3g6So8kqJ1I5RvcJRp4Hya2AcUW3Q2H/jDM075lXR4yZpyyVEloYCK
tre6Skw3TS1mn+6+EkKSHeaAJrpg5S4vqzi+tohNaFukxqI9yK3XFnFDh5hFMxWw7WtCyJ
afuvsvNaHkM4zwA95LJOodiL3vyY2oPqg3SGAsV4zetn5SEW6MwatQ3LVDYhaxLO6CjypZ
pCLItRAvRLG4RnAAABAQDcR1u635Jp3+Dgpxe9sd9FtlMTeIjLKqC74HWsjcp7uXg+MmKj
/u5eFeuY/T2W5ZIQrfTfYrl+e+GcwLqtgD/az8+U4nbKSqbKmHN1TPT0J9W39SnHWFc7E4
o0HJ5YFmatDaceGG52vNAjiX1vtW027g8aANE8wb9NSHZhw7tI6iI1qH0atnjd2FyhaMDc
AADWDspk8LMV+jZ0q/VtICyWmHRb4wUuVG7s4xF4Ys67gYGKjulvGNTUPt2s/xtWP0EzKZ
PBL1VGYMKWLzM6TvkkAv1Hq8oLWslRYNrE0aVA+DK+/udaRGdwwfa7cftLjdlLOxDL32U5
EPmKMmolMAGzAAAAG2ltYXNoc2Fua2FkZWVwYTI3QGdtYWlsLmNvbQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----

port: 22
        source: "."
        target: "/home/${{oakroots}}/repositories"

deployment:
  tasks:
    - export NODE_ENV=production
    - cd backend
    - npm install
    - pm2 restart server.js --name "backend-app" || pm2 start server.js --name "backend-app"
    - cd ../frontend
    - npm install
    - npm run build
    - cp -r build/* ../public_html/

       
